# Generated by Django 4.2.7 on 2023-11-24 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mytask',
            new_name='Todo',
        ),
    ]
